name: Workflows Test by Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create docker network
        run: |
        docker network create mynetwork

      - name: Start Selenium container
        run: |
          docker run --network host --rm --name selenium-container selenium/standalone-chrome:119.0-chromedriver-119.0-grid-4.15.0-20231129

      - name: Wait for Selenium container to start
        run: sleep 30

      - name: Run Tests
        run: |
          docker run --rm -v $PWD/tests:/usr/src/app -w /usr/src/app --network host selenium/standalone-chrome python test_model-graph-speedup.py

